site_name: project_template
site_url: https://embeddedboys.github.io/project_template/
repo_url: https://github.com/embeddedboys/project_template
edit_uri: main/Documentation/docs/

site_description: Wiki of project_template
site_author: embeddedboys developers

copyright: Copyright © 2023 embeddedboys

theme:
  name: material
  language: zh
  font:
    code: Roboto Mono
  # custom_dir: docs/overrides
  logo:
    assets/048-boy-next.png
  palette:
    - scheme: default
      accent: red
      primary: black
      toggle:
        icon: material/lightbulb
        # icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: black
      accent: amber
      toggle:
        icon: material/lightbulb-outline
        # icon: material/toggle-switch
        name: Switch to light mode
  features:
      - search.suggest
      - search.highlight
      - search.share
  #   - navigation.expand
  #   - navigation.indexes
  #   - navigation.sections
  #   - navigation.tabs
  #   - toc.follow
  #   - toc.integrate

nav:
    - 主页: README.md
    - 快速上手:
      - '从这里开始吧': getting-started/index.md
    - 文档:
      - '硬件': hardware/index.md
      - '软件': software/index.md
    - 关于:
        - '开发人员名单': credits.md
        - '许可证': license.md
        - '更新说明': releasenote.md
        - 'FAQs': FAQs.md
    - 致谢: thanks.md

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://embeddedboys.github.io/project_template/
      name: project_template on Github

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - admonition
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

plugins:
  - search
  - i18n:
      docs_structure: suffix
      fallback_to_default: true
      reconfigure_material: true
      reconfigure_search: true
      languages:
        - locale: zh
          default: true
          name: 简体中文
          build: true
          site_name: "project_template"
        - locale: en
          name: English
          build: true
          site_name: "project_template"
          nav_translations:
            主页: Home
            快速上手: Getting started
            配件: Parts
            文档: Wiki
            硬件: Hardware
            软件: Software
            关于: About
            开发人员名单: Credits
            许可证: License
            更新说明: Release Note
            致谢: Thank